// LCE-10000383 — mdl-site portfolio and case study data
// Migrated from motivation-site/src/worker.js

export const SURVEY_URL = 'mailto:chris@motivation.digital'; // TODO: replace with Typeform URL

export const CF_IMG = 'https://imagedelivery.net/8taA81TQ4UD-fca9BHMP5A';

export const PORTFOLIO = [
  {
    i: 'BM',
    name: 'BeMobile Physio',
    cat: 'health-fitness',
    label: 'Health & Fitness',
    result: '$7.6M revenue · 1,000+ signups in 10 hours · 70× growth',
    slug: 'fitness-platform-physiotherapy',
    img: 'https://imagedelivery.net/8taA81TQ4UD-fca9BHMP5A/bem-portal-hero/public',
    client: 'Be Mobile Physiotherapy',
    cardTitle: 'Exercise Platform for Adults 55+',
    cardDesc: 'Physio-led membership platform — scaled from $100k to $8M+ in revenue.',
  },
  {
    i: 'DSC',
    name: 'Dietitian Success Center',
    cat: 'education',
    label: 'Education',
    result: '$150k in 6 months · 2% steady conversion',
    slug: 'healthcare-platform-dietitians',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2164672628/settings_images/6806b87-3e7-55e-45e0-4d6df475c0ba_2f3cb3-6aee-411e-eb5-5cb083df6374_841314-21bb-60f-0b08-cfd67d3d508_image_346.png',
    client: 'Dietitian Success Center',
    cardTitle: 'Healthcare Education Platform',
    cardDesc: 'WordPress-to-membership migration — 500+ resources, freemium funnel, $100k+ recurring revenue.',
  },
  {
    i: 'JDG',
    name: 'JeJoueDeLaGuitare',
    cat: 'education',
    label: 'Music Education',
    result: 'Six figures in 24 hours · 50k+ guitarists',
    slug: 'music-platform-guitar',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/sites/74680/images/fd40207-6fc6-1ac-ccbf-8a1201b3b7ac_Screenshot_2026-02-09_at_14.01.26.png',
    client: 'Je Joue De La Guitare',
    cardTitle: 'Guitar Learning Platform',
    cardDesc: 'Interactive music-education platform — six-figure revenue in 24 hours, 50k+ guitarists onboarded.',
  },
  {
    i: 'GST',
    name: 'GenuineShift',
    cat: 'b2b',
    label: 'B2B',
    result: '$250k contract win · 100+ insurance firms',
    slug: 'b2b-insurance-training-platform',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/sites/74680/images/44dcd1b-70d-c30b-c440-6dbbb21f53__04-02-2026_160122.jpg',
    client: 'GenuineShift',
    cardTitle: 'B2B Insurance Training Platform',
    cardDesc: '$250k contract win from an $8B customer. 100+ insurance firms served nationwide.',
  },
  {
    i: 'QNA',
    name: 'Qina',
    cat: 'health-fitness',
    label: 'Healthtech',
    result: 'Top 10 global nutrition companies · 500+ business listings',
    slug: 'healthtech-platform-qina',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/sites/74680/images/26fed8f-a78-e27-a277-8a30de1666a2__19-02-2026_154546.jpg',
    client: 'Qina',
    cardTitle: 'Nutrition Technology Platform',
    cardDesc: 'Healthtech platform for the global nutrition industry — 500+ business listings, top 10 global nutrition companies.',
  },
  {
    i: 'TRR',
    name: 'Time Rich Recruiter',
    cat: 'b2b',
    label: 'B2B',
    result: '$10M business · 7% organic conversion · 81% live engagement',
    slug: 'recruitment-coaching-platform',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2164633298/settings_images/310d2d7-b27b-dd01-f83b-0fb6b544812e_MD_Case_Studies_1_.png',
    client: 'Time Rich Recruiter',
    cardTitle: 'Recruitment Coaching Platform',
    cardDesc: 'High-ticket coaching platform for a $10M recruitment brand — 7% organic conversion, 81% group coaching engagement.',
  },
  {
    i: 'DBC',
    name: 'DreamBodyClub',
    cat: 'health-fitness',
    label: 'Health & Fitness',
    result: 'Free Health Index · personalised programs · 589 workouts · 316 recipes',
    slug: 'health-platform-dreambody',
    img: 'https://imagedelivery.net/8taA81TQ4UD-fca9BHMP5A/33f2497e-888b-43aa-e9a5-8fd0bb911d00/public',
    client: 'DreamBodyClub',
    cardTitle: 'AI Health & Fitness Platform',
    cardDesc: 'A free Health Index that scores four areas of wellbeing, then builds a personalised program — with a 589-workout and 316-recipe library that adapts to her life.',
  },
  {
    i: 'MX',
    name: 'Mixmasters',
    cat: 'education',
    label: 'Music & Community',
    result: 'Six-figure music collaboration platform',
    slug: 'music-collaboration-platform',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2164808801/settings_images/cc3c848-35bf-50f1-fb16-4418e311a086_Group_427321080.png',
    client: 'Mixmasters',
    cardTitle: 'Music Collaboration Platform',
    cardDesc: 'A community-focused platform for DJs and producers to collaborate, share tracks, and exchange feedback.',
  },
  {
    i: 'GKR',
    name: 'GKR Karate',
    cat: 'health-fitness',
    label: 'Health & Fitness',
    result: '3,000+ active members · 500+ on-demand videos · 87% monthly engagement',
    slug: 'martial-arts-platform',
    img: 'https://imagedelivery.net/8taA81TQ4UD-fca9BHMP5A/gkr-portal-hero/public',
    client: 'GKR Karate',
    cardTitle: 'Martial Arts Membership Platform',
    cardDesc: 'Global online dojo for GKR Karate International — 3,000+ active members, 87% monthly engagement.',
  },
  {
    i: 'STF',
    name: 'SpeechTimeFun',
    cat: 'education',
    label: 'Education',
    result: '$1.8M+ revenue · 9,000+ members · 1,000+ SLP materials',
    slug: 'speech-education-platform',
    img: 'https://kajabi-storefronts-production.kajabi-cdn.com/kajabi-storefronts-production/file-uploads/themes/2164668351/settings_images/aa1a24f-e880-55c8-d122-beb4c441c6ae_stf0023.png',
    client: 'SpeechTimeFun',
    cardTitle: 'Speech Therapy Education Platform',
    cardDesc: 'ThriveCart-to-Kajabi migration — 9,000+ SLP members, 1,000+ materials, $1.8M+ revenue.',
  },
  {
    i: 'TCP',
    name: 'Trust Center Pro',
    cat: 'b2b',
    label: 'B2B SaaS',
    result: '54+ jurisdictions · 60-second compliance scan',
    slug: 'compliance-privacy-platform',
    img: 'https://imagedelivery.net/8taA81TQ4UD-fca9BHMP5A/tcp-portal-hero/public',
    client: 'Trust Center Pro',
    cardTitle: 'Website Compliance, Automated',
    cardDesc: 'Multi-tenant compliance SaaS — automated scanning, consent management, and policy hub for any brand, any jurisdiction.',
  },
  {
    i: 'SV',
    name: 'Studio.video',
    cat: 'b2b',
    label: 'B2B SaaS',
    result: 'Branded browser meetings · up to 5,000 attendees · 100% EU-hosted',
    slug: 'video-meeting-platform',
    img: 'https://customer-4x18g7wq6et2wysi.cloudflarestream.com/e2e237d10b065a909b2cebe7445dfb8f/thumbnails/thumbnail.jpg?time=2s&height=480',
    client: 'Studio.video',
    cardTitle: 'Branded Video Meeting Platform',
    cardDesc: 'White-label meeting rooms, webinars and client sessions on your own domain — browser-based, EU-hosted, with AI recaps built in.',
  },
];

// Slugs used by getStaticPaths
export const SLUGS = PORTFOLIO.filter(p => p.slug).map(p => p.slug);
