#!/usr/bin/env node
// Builds the production worker for mdl-site (motivation.digital). LCE-10000383.
//
// 1. Reads dist/client/ and writes dist-worker/assets.js — an ES module exporting the
//    static asset map (all HTML pages + JS/CSS/images, base64 for binaries).
// 2. esbuild-bundles scripts/worker-runtime.js into a single self-contained module
//    worker at dist-worker/worker.js.
//
// No D1 bindings — motivation.digital is a purely static site.

import { readFileSync, readdirSync, statSync, mkdirSync, writeFileSync } from 'fs';
import { join, relative } from 'path';
import { build } from 'esbuild';

const CLIENT_DIR = 'dist/client';
const OUT_DIR = 'dist-worker';
const ASSETS_FILE = join(OUT_DIR, 'assets.js');
const OUT_FILE = join(OUT_DIR, 'worker.js');

function mimeFor(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8';
  if (path.endsWith('.css')) return 'text/css; charset=utf-8';
  if (path.endsWith('.js') || path.endsWith('.mjs')) return 'application/javascript; charset=utf-8';
  if (path.endsWith('.json')) return 'application/json; charset=utf-8';
  if (path.endsWith('.svg')) return 'image/svg+xml; charset=utf-8';
  if (path.endsWith('.png')) return 'image/png';
  if (path.endsWith('.jpg') || path.endsWith('.jpeg')) return 'image/jpeg';
  if (path.endsWith('.webp')) return 'image/webp';
  if (path.endsWith('.ico')) return 'image/x-icon';
  if (path.endsWith('.woff2')) return 'font/woff2';
  if (path.endsWith('.woff')) return 'font/woff';
  if (path.endsWith('.txt')) return 'text/plain; charset=utf-8';
  if (path.endsWith('.xml')) return 'application/xml; charset=utf-8';
  return 'application/octet-stream';
}

function walk(dir) {
  const entries = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) entries.push(...walk(full));
    else entries.push(full);
  }
  return entries;
}

const files = walk(CLIENT_DIR);
const assets = [];

for (const file of files) {
  const rel = relative(CLIENT_DIR, file).replace(/\\/g, '/');
  if (rel === '.assetsignore') continue;
  const content = readFileSync(file);
  const isText = /\.(html|css|js|mjs|json|svg|txt|xml)$/.test(file);
  const path = '/' + rel;
  const mime = mimeFor(file);
  if (isText) assets.push({ path, text: content.toString('utf8'), mime });
  else assets.push({ path, b64: content.toString('base64'), mime });
}

mkdirSync(OUT_DIR, { recursive: true });

// --- 1. Asset map module ---
let assetCode = '// AUTO-GENERATED by scripts/build-worker.js — do not edit\n';
assetCode += 'export const ASSETS = new Map([\n';
for (const a of assets) {
  if (a.text !== undefined) {
    assetCode += `  [${JSON.stringify(a.path)}, { t: ${JSON.stringify(a.text)}, m: ${JSON.stringify(a.mime)} }],\n`;
  } else {
    assetCode += `  [${JSON.stringify(a.path)}, { b: ${JSON.stringify(a.b64)}, m: ${JSON.stringify(a.mime)} }],\n`;
  }
}
assetCode += ']);\n';
writeFileSync(ASSETS_FILE, assetCode);

// --- 2. Bundle the worker runtime ---
await build({
  entryPoints: ['scripts/worker-runtime.js'],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  outfile: OUT_FILE,
  legalComments: 'none',
});

const bytes = statSync(OUT_FILE).size;
console.log(`Generated ${OUT_FILE} with ${assets.length} assets (${Math.round(bytes / 1024)}KB bundle)`);
